name: Ensure HTTPS

on:
  pull_request:

jobs:
  https:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: .github/EnsureHttps.ps1
        shell: pwsh

